### ISSUE TITLE
Caused the server to crash in the Fabric 1.19.2 server

### ISSUE THREAD

**Issue by CUX-LI** [Declipsonator/Rain-Growth#2]
Caused the server to crash in the Fabric 1.19.2 server

**Comment by venaminecraft** [comment]
Hello @Declipsonator and thank you @CUX-LI for reporting the issue.
I was trying the mod on 1.19.3 - everything loads fine.

**When it starts to rain I get this crash log:**
Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchFieldError: field_9229
        at net.minecraft.class_3218.handler$znb000$speedUpTicksIfRain(class_3218.java:5239) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18203(class_3218.java:464) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:380) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:324) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:322) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        ... 5 more
